function drawPC_F6(result1,data,str)
% figure
t = tiledlayout('flow');
t.TileSpacing = 'tight';
t.Padding = 'tight';
nexttile
hold on
plot(data.node(data.noD,1),data.node(data.noD,2),'ro','LineWidth',2,...
    'MarkerEdgeColor','k',...
    'MarkerFaceColor','y',...
    'MarkerSize',8)
plot(data.node(data.noC,1),data.node(data.noC,2),'rs','LineWidth',2,...
    'MarkerEdgeColor','k',...
    'MarkerFaceColor','g',...
    'MarkerSize',12)
plot(data.node(data.noP,1),data.node(data.noP,2),'rh','LineWidth',2,...
    'MarkerEdgeColor','k',...
    'MarkerFaceColor','b',...
    'MarkerSize',10)
plot(data.node(result1.selectedC0,1),data.node(result1.selectedC0,2),'*','LineWidth',2,...
    'MarkerEdgeColor','r',...
    'MarkerFaceColor','r',...
    'MarkerSize',10)
for i=1:length(result1.recording(:,1))
    path1=result1.recording(i,5:6);
    noS=result1.recording(i,2);
    plot(data.node(path1,1),data.node(path1,2),'-k','LineWidth',1.5,'Color',data.color(noS,:))
    path2=result1.recording(i,4:5);
    plot(data.node(path2,1),data.node(path2,2),'-k','LineWidth',1,...
    'MarkerEdgeColor','k',...
    'MarkerFaceColor','b',...
    'MarkerSize',10)
end
legend('需求点','备选物流中心','生产点','已选中心')
title([str,'，总目标',num2str(result1.fit)])
% figure
nexttile
hold on
plot(data.node(data.noD,1),data.node(data.noD,2),'ro','LineWidth',2,...
    'MarkerEdgeColor','k',...
    'MarkerFaceColor','y',...
    'MarkerSize',8)
plot(data.node(data.noC,1),data.node(data.noC,2),'rs','LineWidth',2,...
    'MarkerEdgeColor','k',...
    'MarkerFaceColor','g',...
    'MarkerSize',12)

plot(data.node(data.noP,1),data.node(data.noP,2),'rh','LineWidth',2,...
    'MarkerEdgeColor','k',...
    'MarkerFaceColor','b',...
    'MarkerSize',10)
plot(data.node(result1.selectedC0,1),data.node(result1.selectedC0,2),'*','LineWidth',2,...
    'MarkerEdgeColor','r',...
    'MarkerFaceColor','r',...
    'MarkerSize',10)
legend('需求点','备选物流中心','生产点','已选中心')
title([str,'，总目标',num2str(result1.fit)])
disp(['最优中转枢纽为：',num2str(result1.selectedC0')])
disp(['具体城市为：']);
for i=1:length(result1.selectedC0)
    disp(data.node0{result1.selectedC0(i)+1,1})
end
disp('各中转枢纽负载：')
disp(result1.demandC)
disp(['固定成本：',num2str(result1.C1)])
disp(['运输成本1：',num2str(result1.C21)])
disp(['运输成本2：',num2str(result1.C22)])
disp(['可变成本：',num2str(result1.C3)])
disp(['库存成本：',num2str(result1.C4)])
end